# Generated by Django 5.1.4 on 2024-12-28 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('ONLINE', 'ONLINE'), ('COD', 'COD')], default='COB', max_length=100)),
                ('RZP_order_id', models.CharField(max_length=200, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.basemodel')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('order_confirmed', 'Order confirmed'), ('dispatched', 'Dispatched'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='order_confirmed', max_length=200)),
                ('body_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.lightbodycolour')),
                ('colour_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.lightcolour')),
                ('light_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.light')),
                ('order_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='shop.order')),
                ('shape_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shape')),
            ],
            bases=('shop.basemodel',),
        ),
    ]
